[package]
name = "ekdesktop/tomfoolery"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
axis = "sleitnick/axis@0.1.0"
matter = "evaera/matter@0.1.2"