[package]
name = "alreadypro/profileservice"
description = "A fork of MadStudioRoblox/ProfileService"
version = "1.0.4"
license = "MIT OR Apache-2.0"
authors = [
	"loleris (https://github.com/LM-loleris)",
	"AlreadyPro (https://github.com/AlreadyPro)"
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]