[package]
name = "nightcycle/rx"
description = "rx"
version = "3.7.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
promise = "quenty/promise@3.1.3-canary"
signal = "quenty/signal@2.0.0-canary"
maid = "quenty/maid@2.0.1-canary"
