[package]
name = "quenty/maid"
description = "Easily cleanup event listeners and objects in Roblox."
version = "2.0.1-canary.140ed9d6.1"
license = "MIT"
authors = ["James Onnen"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None!