[package]
name = "quenty/signal"
description = "A simple signal implementation for Roblox."
version = "2.0.0-canary.140ed9d6.2"
license = "MIT"
authors = ["James Onnen"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None!