[package]
name = "quenty/promise"
description = "Promise implementation for Roblox"
version = "3.1.3-canary.140ed9d6.4"
license = "MIT"
authors = ["James Onnen"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
loader = "quenty/loader@3.1.1-canary"
Maid = "quenty/maid@2.0.1-canary"