[package]
name = "shanebutt/llama"
version = "1.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["bin", "docs", "modules", "tests", "**.toml"]
include = ["wally.toml", "Packages"]

[dependencies]
t = "osyrisrblx/t@3.0.0"